# Generated by Django 6.1 on 2026-08-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('functional_rep', 'Functional Representative'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
