# Generated by Django 6.1 on 2026-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='query_categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of categories (e.g., Policy, CSR)', max_length=500),
        ),
    ]
