# Generated by Django 6.1 on 2026-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team_query_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auto_close_hours',
            field=models.IntegerField(default=72, help_text='Hours after resolved before auto-close'),
        ),
        migrations.AddField(
            model_name='team',
            name='canned_responses',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of canned responses'),
        ),
        migrations.AddField(
            model_name='team',
            name='sla_hours',
            field=models.IntegerField(default=24, help_text='Target resolution time in hours'),
        ),
    ]
