# Generated by Django 6.1 on 2026-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_employee_number_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(default='HR Servicedesk', max_length=100)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=20)),
                ('secondary_color', models.CharField(default='#14b8a6', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
    ]
