# Generated by Django 6.1 on 2026-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='auto_close_hours',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sla_hours',
        ),
        migrations.AddField(
            model_name='team',
            name='auto_close_days',
            field=models.IntegerField(default=3, help_text='Days after resolved before auto-close'),
        ),
        migrations.AddField(
            model_name='team',
            name='sla_days',
            field=models.IntegerField(default=1, help_text='Target resolution time in days'),
        ),
    ]
