# Generated by Django 6.1 on 2026-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_team_auto_close_hours_remove_team_sla_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='workflow_rules',
            field=models.TextField(blank=True, default='[]', help_text="JSON array of workflow rules (e.g. [{'keyword': 'payroll', 'priority': 'urgent'}])"),
        ),
    ]
