# Generated by Django 6.1 on 2026-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_team_workflow_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_prefs',
            field=models.TextField(blank=True, default='{}', help_text='JSON preferences for dashboard widgets'),
        ),
    ]
