# Generated by Django 6.1 on 2026-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_dashboard_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='dashboard_palette',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
