# Generated by Django 6.1 on 2026-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_branding_dashboard_palette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='dashboard_palette',
        ),
        migrations.AddField(
            model_name='branding',
            name='chart_color_1',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='chart_color_2',
            field=models.CharField(default='#14b8a6', max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='chart_color_3',
            field=models.CharField(default='#f59e0b', max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='chart_color_4',
            field=models.CharField(default='#ef4444', max_length=20),
        ),
        migrations.AddField(
            model_name='branding',
            name='chart_color_5',
            field=models.CharField(default='#8b5cf6', max_length=20),
        ),
    ]
