# Generated by Django 6.1 on 2026-08-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_branding_dashboard_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='ticket_reopen_window_days',
            field=models.IntegerField(default=15),
        ),
    ]
