# Generated by Django 6.1 on 2026-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_branding_ticket_reopen_window_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='SMTP server hostname, e.g. smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, help_text='Sender address shown to recipients', max_length=254)),
                ('enabled', models.BooleanField(default=False, help_text='When checked, these settings override environment variables')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
    ]
