# Generated by Django 5.2.17 on 2026-09-06 17:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_branding_ticket_reopen_window_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[users.models.validate_branding_image]),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[users.models.validate_branding_image]),
        ),
    ]
