# Generated by Django 6.1 on 2026-08-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
    ]
