# Generated by Django 6.1 on 2026-08-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_query_relevance_alter_ticket_priority_and_more'),
        ('users', '0004_team_auto_close_hours_team_canned_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='users.team'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
    ]
