# Generated by Django 6.1 on 2026-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_attachment_team_ticket_is_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
