# Generated by Django 6.1 on 2026-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
