# Generated by Django 6.1 on 2026-08-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_has_unread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kb_files/'),
        ),
    ]
