# Generated by Django 5.2.17 on 2026-09-06 17:03

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', validators=[tickets.models.validate_attachment_file]),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kb_files/', validators=[tickets.models.validate_attachment_file]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
    ]
